grep -l '"about.html"' ./*html | xargs sed -i.bak -e 's/\"about.html\"/\"\/srs\/_about.html\"/g'
grep -l '"index.html"' ./*html | xargs sed -i.bak -e 's/\"index.html\"/\"/\"/g'
grep -l '"index.html"' ./*html | xargs sed -i.bak -e 's/\"index.html\"/\"\/\"/g'
grep -l '"bt-beginner.html"' ./*html | xargs sed -i.bak -e 's/\"bt-beginner.html\"/\"\/srs\/_bt-beginner.html\"/g'
grep -l '"bt-event.html"' ./*html | xargs sed -i.bak -e 's/\"bt-event.html\"/\"\/srs\/_bt-event.html\"/g'
grep -l '"bt-guide-top.html"' ./*html | xargs sed -i.bak -e 's/\"bt-guide-top.html\"/\"\/srs\/_bt-guide-top.html\"/g'
grep -l '"bt-info-top.html"' ./*html | xargs sed -i.bak -e 's/\"bt-info-top.html\"/\"\/srs\/_bt-info-top.html\"/g'
grep -l '"bt-law.html"' ./*html | xargs sed -i.bak -e 's/\"bt-law.html\"/\"\/srs\/_bt-law.html\"/g'
grep -l '"bt-purchase-flow.html"' ./*html | xargs sed -i.bak -e 's/\"bt-purchase-flow.html\"/\"\/srs\/_bt-purchase-flow.html\"/g'
grep -l '"bt-select.html"' ./*html | xargs sed -i.bak -e 's/\"bt-select.html\"/\"\/srs\/_bt-select.html\"/g'
grep -l '"bt-trouble-support.html"' ./*html | xargs sed -i.bak -e 's/\"bt-trouble-support.html\"/\"\/srs\/_bt-trouble-support.html\"/g'
grep -l '"construction-flow.html"' ./*html | xargs sed -i.bak -e 's/\"construction-flow.html\"/\"\/srs\/_construction-flow.html\"/g'
grep -l '"corporate.html"' ./*html | xargs sed -i.bak -e 's/\"corporate.html\"/\"\/srs\/_corporate.html\"/g'
grep -l '"customize.html"' ./*html | xargs sed -i.bak -e 's/\"custmize.html\"/\"\/srs\/_custmize.html\"/g'
grep -l '"customize.html"' ./*html | xargs sed -i.bak -e 's/\"customize.html\"/\"\/srs\/_customize.html\"/g'
grep -l '"exhibit.html"' ./*html | xargs sed -i.bak -e 's/\"exhibit.html\"/\"\/srs\/_exhibit.html\"/g'
grep -l '"installation.html"' ./*html | xargs sed -i.bak -e 's/\"installation.html\"/\"\/srs\/_installation.html\"/g'
grep -l '"office.html"' ./*html | xargs sed -i.bak -e 's/\"office.html\"/\"\/srs\/_office.html\"/g'
grep -l '"pm-beginner.html"' ./*html | xargs sed -i.bak -e 's/\"pm-beginner.html\"/\"\/srs\/_pm-beginner.html\"/g'
grep -l '"pm-event.html"' ./*html | xargs sed -i.bak -e 's/\"pm-event.html\"/\"\/srs\/_pm-event.html\"/g'
grep -l '"pm-faq.html"' ./*html | xargs sed -i.bak -e 's/\"pm-faq.html\"/\"\/srs\/_pm-faq.html\"/g'
grep -l '"pm-guide-top.html"' ./*html | xargs sed -i.bak -e 's/\"pm-guide-top.html\"/\"\/srs\/_pm-guide-top.html\"/g'
grep -l '"pm-info-top.html"' ./*html | xargs sed -i.bak -e 's/\"pm-info-top.html\"/\"\/srs\/_pm-info-top.html\"/g'
grep -l '"pm-law.html"' ./*html | xargs sed -i.bak -e 's/\"pm-law.html\"/\"\/srs\/_pm-law.html\"/g'
grep -l '"pm-purchase-flow.html"' ./*html | xargs sed -i.bak -e 's/\"pm-purchase-flow.html\"/\"\/srs\/_pm-purchase-flow.html\"/g'
grep -l '"pm-select.html"' ./*html | xargs sed -i.bak -e 's/\"pm-select.html\"/\"\/srs\/_pm-select.html\"/g'
grep -l '"privacy.html"' ./*html | xargs sed -i.bak -e 's/\"privacy.html\"/\"\/srs\/_privacy.html\"/g'
grep -l '"un-beginner.html"' ./*html | xargs sed -i.bak -e 's/\"un-beginner.html\"/\"\/srs\/_un-beginner.html\"/g'
grep -l '"un-event.html"' ./*html | xargs sed -i.bak -e 's/\"un-event.html\"/\"\/srs\/_un-event.html\"/g'
grep -l '"un-faq.html"' ./*html | xargs sed -i.bak -e 's/\"un-faq.html\"/\"\/srs\/_un-faq.html\"/g'
grep -l '"un-guide-top.html"' ./*html | xargs sed -i.bak -e 's/\"un-guide-top.html\"/\"\/srs\/_un-guide-top.html\"/g'
grep -l '"un-info-top.html"' ./*html | xargs sed -i.bak -e 's/\"un-info-top.html\"/\"\/srs\/_un-info-top.html\"/g'
grep -l '"un-law.html"' ./*html | xargs sed -i.bak -e 's/\"un-law.html\"/\"\/srs\/_un-law.html\"/g'
grep -l '"un-purchase-flow.html"' ./*html | xargs sed -i.bak -e 's/\"un-purchase-flow.html\"/\"\/srs\/_un-purchase-flow.html\"/g'
grep -l '"un-select.html"' ./*html | xargs sed -i.bak -e 's/\"un-select.html\"/\"\/srs\/_un-select.html\"/g'
grep -l '"unitproducts-about.html"' ./*html | xargs sed -i.bak -e 's/\"unitproducts-about.html\"/\"\/srs\/_unitproducts-about.html\"/g'
grep -l '"unitproducts.html"' ./*html | xargs sed -i.bak -e 's/\"unitproducts.html\"/\"\/unitproducts\"/g'
grep -l '"pmproducts.html"' ./*html | xargs sed -i.bak -e 's/\"pmproducts.html\"/\"\/pmproducts\"/g'
grep -l '"btproducts.html"' ./*html | xargs sed -i.bak -e 's/\"btproducts.html\"/\"\/btproducts\"/g'
#
grep -l '"un-search.html"' ./*html | xargs sed -i.bak -e 's/\"un-search.html\"/\"\/un-search\"/g'
grep -l '"pm-search.html"' ./*html | xargs sed -i.bak -e 's/\"pm-search.html\"/\"\/pm-search\"/g'
grep -l '"bt-search.html"' ./*html | xargs sed -i.bak -e 's/\"bt-search.html\"/\"\/bt-search\"/g'
#
grep -l '"feature.html"' ./*html | xargs sed -i.bak -e 's/\"feature.html\"/\"\/srs\/_feature.html\"/g'
grep -l '"sitemap.html"' ./*html | xargs sed -i.bak -e 's/\"sitemap.html\"/\"\/srs\/_sitemap.html\"/g'
grep -l '"commerce.html"' ./*html | xargs sed -i.bak -e 's/\"commerce.html\"/\"\/srs\/_commerce.html\"/g'
grep -l '"bt-purchase-service.html"' ./*html | xargs sed -i.bak -e 's/\"bt-purchase-service.html\"/\"\/srs\/_bt-purchase-service.html\"/g'
grep -l '"pm-purchase-service.html"' ./*html | xargs sed -i.bak -e 's/\"pm-purchase-service.html\"/\"\/srs\/_pm-purchase-service.html\"/g'
grep -l '"un-purchase-service.html"' ./*html | xargs sed -i.bak -e 's/\"un-purchase-service.html\"/\"\/srs\/_un-purchase-service.html\"/g'
# 
grep -l '"/srs/_un-contact.html"' ./*html | xargs sed -i.bak -e 's/\"\/srs\/_un-contact.html\"/\"\/un-contact\"/g'
grep -l '"/srs/_pm-contact.html"' ./*html | xargs sed -i.bak -e 's/\"\/srs\/_pm-contact.html\"/\"\/pm-contact\"/g'
grep -l '"/srs/_bt-contact.html"' ./*html | xargs sed -i.bak -e 's/\"\/srs\/_bt-contact.html\"/\"\/bt-contact\"/g'
#
#grep -l '高所作業車 他' ./*html | xargs sed -i.bak -e 's/高所作業車 他/高所作業車・仮設機材/g'
#grep -l '<br><a href="/srs/_commerce.html">特定商取引に関する表示</a> |' ./*html | xargs sed -i.bak -e 's/<br><a href=\"\/srs\/_commerce.html\">特定商取引に関する表示<\/a> |//g'
